In [3]:
array=[23,45,67,87]
print(array)

[23, 45, 67, 87]


In [21]:
import numpy as np
arr1=np.array([12,34,56,33])
print(arr1)

[12 34 56 33]


In [19]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np
arr3=np.array([[[34,45,88,33],[12,11,14,15],[55,99,00,22]]])
print(arr3)

[[[34 45 88 33]
  [12 11 14 15]
  [55 99  0 22]]]


In [23]:
print(arr2.ndim) 

2


In [25]:
print(arr1.ndim) 

1


In [27]:
print(arr3.ndim) 

3


In [33]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,3])

4


In [39]:
import numpy as pd
arr=np.array([[1,2,3,4,9,7],[2,4,5,6,5,4]])
print(arr[1,4])

5


In [41]:
print(arr[0,2])

3


In [45]:
print(arr3[0,1,2])

14


In [47]:
import numpy as np
arr3=np.array([[[3,4,8],[1,3,9]],[[9,0,2],[12,67,88]]])
print(arr3)

[[[ 3  4  8]
  [ 1  3  9]]

 [[ 9  0  2]
  [12 67 88]]]


In [49]:
print(arr3[0,1,1])

3


In [51]:
print(arr3[1,1,2])

88


In [67]:
print(arr1[1:3])

[34 56]


In [21]:
import numpy as np
arr1=np.array([12,34,56,33])
print(arr1)

[12 34 56 33]


In [71]:
print(arr1[0:3])

[12 34 56]


In [75]:
print(arr3.shape)

(2, 2, 3)


In [77]:
print(arr.shape)

(2, 6)


In [83]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(5,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [85]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
newarr=arr.reshape(9,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


In [89]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,89,56,43,12,56,98,12,6])
newarr=arr.reshape(2,9import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(5,2)
print(newarr))
print(newarr)

[[ 1  2  3  4  5  6  7  8  9]
 [10 89 56 43 12 56 98 12  6]]


In [95]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,12,11])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [12 11]]]
